CREATE SCHEMA IF NOT EXISTS `entregablinddh` DEFAULT CHARACTER SET utf8 ;
USE `entregablinddh` ;

CREATE TABLE IF NOT EXISTS `entregablinddh`.`UNIDADES` (
  `id` INT(11) NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `fecha_inicio` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `entregablinddh`.`CLASES` (
  `id` INT(11) NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `fecha_inicio` DATETIME NOT NULL,
  `visibilidad` TINYINT(4) NOT NULL,
  `UNIDADES_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `UNIDADES_id`),
  INDEX `fk_CLASES_UNIDADES1_idx` (`UNIDADES_id`),
  CONSTRAINT `fk_CLASES_UNIDADES1`
    FOREIGN KEY (`UNIDADES_id`)
    REFERENCES `entregablinddh`.`UNIDADES` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `entregablinddh`.`CONTENIDO` (
  `id` INT(11) NOT NULL,
  `nombre_contenido` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `entregablinddh`.`TIPO_BLOQUE` (
  `id` INT(11) NOT NULL,
  `nombre_tipo_bloque` VARCHAR(45) NOT NULL,
  `CONTENIDO_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `CONTENIDO_id`),
  INDEX `fk_TIPO_BLOQUE_CONTENIDO1_idx` (`CONTENIDO_id`),
  CONSTRAINT `fk_TIPO_BLOQUE_CONTENIDO1`
    FOREIGN KEY (`CONTENIDO_id`)
    REFERENCES `entregablinddh`.`CONTENIDO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `entregablinddh`.`BLOQUES` (
  `id` INT(11) NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `visibilidad` TINYINT(4) NOT NULL,
  `CLASES_id` INT(11) NOT NULL,
  `TIPO_BLOQUE_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `CLASES_id`, `TIPO_BLOQUE_id`),
  INDEX `fk_BLOQUES_CLASES1_idx` (`CLASES_id` ASC),
  INDEX `fk_BLOQUES_TIPO_BLOQUE1_idx` (`TIPO_BLOQUE_id` ASC),
  CONSTRAINT `fk_BLOQUES_CLASES1`
    FOREIGN KEY (`CLASES_id`)
    REFERENCES `entregablinddh`.`CLASES` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BLOQUES_TIPO_BLOQUE1`
    FOREIGN KEY (`TIPO_BLOQUE_id`)
    REFERENCES `entregablinddh`.`TIPO_BLOQUE` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `entregablinddh`.`CATEGORIAS` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_categ` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `entregablinddh`.`CURSOS` (
  `id` INT(11) NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `imagen` VARCHAR(45) NOT NULL,
  `fecha_inicio` DATETIME NOT NULL,
  `fecha_final` VARCHAR(45) NOT NULL,
  `cupo_curso` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `entregablinddh`.`USUARIOS` (
  `id` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `CATEGORIAS_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `CATEGORIAS_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_USUARIOS_CATEGORIAS1_idx` (`CATEGORIAS_id` ASC),
  CONSTRAINT `fk_USUARIOS_CATEGORIAS1`
    FOREIGN KEY (`CATEGORIAS_id`)
    REFERENCES `entregablinddh`.`CATEGORIAS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `entregablinddh`.`CURSOS_has_USUARIOS` (
  `CURSOS_id` INT(11) NOT NULL,
  `USUARIOS_id` INT(11) NOT NULL,
  PRIMARY KEY (`CURSOS_id`, `USUARIOS_id`),
  INDEX `fk_CURSOS_has_USUARIOS_USUARIOS1_idx` (`USUARIOS_id` ASC) ,
  INDEX `fk_CURSOS_has_USUARIOS_CURSOS1_idx` (`CURSOS_id` ASC) ,
  CONSTRAINT `fk_CURSOS_has_USUARIOS_CURSOS1`
    FOREIGN KEY (`CURSOS_id`)
    REFERENCES `entregablinddh`.`CURSOS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CURSOS_has_USUARIOS_USUARIOS1`
    FOREIGN KEY (`USUARIOS_id`)
    REFERENCES `entregablinddh`.`USUARIOS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `entregablinddh`.`UNIDADES_has_CURSOS` (
  `UNIDADES_id` INT(11) NOT NULL,
  `CURSOS_id` INT(11) NOT NULL,
  PRIMARY KEY (`UNIDADES_id`, `CURSOS_id`),
  INDEX `fk_UNIDADES_has_CURSOS_CURSOS1_idx` (`CURSOS_id` ASC) ,
  INDEX `fk_UNIDADES_has_CURSOS_UNIDADES1_idx` (`UNIDADES_id` ASC) ,
  CONSTRAINT `fk_UNIDADES_has_CURSOS_CURSOS1`
    FOREIGN KEY (`CURSOS_id`)
    REFERENCES `entregablinddh`.`CURSOS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UNIDADES_has_CURSOS_UNIDADES1`
    FOREIGN KEY (`UNIDADES_id`)
    REFERENCES `entregablinddh`.`UNIDADES` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)